// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: supersand.proto

package rpc_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Errors int32

const (
	Errors_Internal_Server_Error Errors = 0
	Errors_UserNotFound          Errors = 1
	Errors_UserNotValid          Errors = 2
	Errors_UserLimit_full        Errors = 3
	Errors_Not_Accessable        Errors = 4
	Errors_Resorces_Are_busy     Errors = 5
	Errors_Invalide_token        Errors = 6
)

// Enum value maps for Errors.
var (
	Errors_name = map[int32]string{
		0: "Internal_Server_Error",
		1: "UserNotFound",
		2: "UserNotValid",
		3: "UserLimit_full",
		4: "Not_Accessable",
		5: "Resorces_Are_busy",
		6: "Invalide_token",
	}
	Errors_value = map[string]int32{
		"Internal_Server_Error": 0,
		"UserNotFound":          1,
		"UserNotValid":          2,
		"UserLimit_full":        3,
		"Not_Accessable":        4,
		"Resorces_Are_busy":     5,
		"Invalide_token":        6,
	}
)

func (x Errors) Enum() *Errors {
	p := new(Errors)
	*p = x
	return p
}

func (x Errors) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Errors) Descriptor() protoreflect.EnumDescriptor {
	return file_supersand_proto_enumTypes[0].Descriptor()
}

func (Errors) Type() protoreflect.EnumType {
	return &file_supersand_proto_enumTypes[0]
}

func (x Errors) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Errors.Descriptor instead.
func (Errors) EnumDescriptor() ([]byte, []int) {
	return file_supersand_proto_rawDescGZIP(), []int{0}
}

type Errordetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Errors                 `protobuf:"varint,1,opt,name=code,proto3,enum=rpc_api.Errors" json:"code,omitempty"`
	Messagefordev string                 `protobuf:"bytes,2,opt,name=messagefordev,proto3" json:"messagefordev,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Errordetails) Reset() {
	*x = Errordetails{}
	mi := &file_supersand_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Errordetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Errordetails) ProtoMessage() {}

func (x *Errordetails) ProtoReflect() protoreflect.Message {
	mi := &file_supersand_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Errordetails.ProtoReflect.Descriptor instead.
func (*Errordetails) Descriptor() ([]byte, []int) {
	return file_supersand_proto_rawDescGZIP(), []int{0}
}

func (x *Errordetails) GetCode() Errors {
	if x != nil {
		return x.Code
	}
	return Errors_Internal_Server_Error
}

func (x *Errordetails) GetMessagefordev() string {
	if x != nil {
		return x.Messagefordev
	}
	return ""
}

type InitRequset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequset) Reset() {
	*x = InitRequset{}
	mi := &file_supersand_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequset) ProtoMessage() {}

func (x *InitRequset) ProtoReflect() protoreflect.Message {
	mi := &file_supersand_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequset.ProtoReflect.Descriptor instead.
func (*InitRequset) Descriptor() ([]byte, []int) {
	return file_supersand_proto_rawDescGZIP(), []int{1}
}

func (x *InitRequset) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type UserLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authkey       string                 `protobuf:"bytes,1,opt,name=Authkey,proto3" json:"Authkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginRequest) Reset() {
	*x = UserLoginRequest{}
	mi := &file_supersand_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginRequest) ProtoMessage() {}

func (x *UserLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supersand_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginRequest.ProtoReflect.Descriptor instead.
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return file_supersand_proto_rawDescGZIP(), []int{2}
}

func (x *UserLoginRequest) GetAuthkey() string {
	if x != nil {
		return x.Authkey
	}
	return ""
}

type StatusComandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SesonID       string                 `protobuf:"bytes,1,opt,name=sesonID,proto3" json:"sesonID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusComandRequest) Reset() {
	*x = StatusComandRequest{}
	mi := &file_supersand_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusComandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusComandRequest) ProtoMessage() {}

func (x *StatusComandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supersand_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusComandRequest.ProtoReflect.Descriptor instead.
func (*StatusComandRequest) Descriptor() ([]byte, []int) {
	return file_supersand_proto_rawDescGZIP(), []int{3}
}

func (x *StatusComandRequest) GetSesonID() string {
	if x != nil {
		return x.SesonID
	}
	return ""
}

type InitRespons struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SesonID       string                 `protobuf:"bytes,1,opt,name=sesonID,proto3" json:"sesonID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRespons) Reset() {
	*x = InitRespons{}
	mi := &file_supersand_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRespons) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRespons) ProtoMessage() {}

func (x *InitRespons) ProtoReflect() protoreflect.Message {
	mi := &file_supersand_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRespons.ProtoReflect.Descriptor instead.
func (*InitRespons) Descriptor() ([]byte, []int) {
	return file_supersand_proto_rawDescGZIP(), []int{4}
}

func (x *InitRespons) GetSesonID() string {
	if x != nil {
		return x.SesonID
	}
	return ""
}

type UserLoginRespons struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginRespons) Reset() {
	*x = UserLoginRespons{}
	mi := &file_supersand_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginRespons) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginRespons) ProtoMessage() {}

func (x *UserLoginRespons) ProtoReflect() protoreflect.Message {
	mi := &file_supersand_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginRespons.ProtoReflect.Descriptor instead.
func (*UserLoginRespons) Descriptor() ([]byte, []int) {
	return file_supersand_proto_rawDescGZIP(), []int{5}
}

func (x *UserLoginRespons) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type StatusComandRespons struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uptime        int32                  `protobuf:"varint,1,opt,name=Uptime,proto3" json:"Uptime,omitempty"`
	ResourceUsage int32                  `protobuf:"varint,2,opt,name=Resource_usage,json=ResourceUsage,proto3" json:"Resource_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusComandRespons) Reset() {
	*x = StatusComandRespons{}
	mi := &file_supersand_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusComandRespons) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusComandRespons) ProtoMessage() {}

func (x *StatusComandRespons) ProtoReflect() protoreflect.Message {
	mi := &file_supersand_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusComandRespons.ProtoReflect.Descriptor instead.
func (*StatusComandRespons) Descriptor() ([]byte, []int) {
	return file_supersand_proto_rawDescGZIP(), []int{6}
}

func (x *StatusComandRespons) GetUptime() int32 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *StatusComandRespons) GetResourceUsage() int32 {
	if x != nil {
		return x.ResourceUsage
	}
	return 0
}

var File_supersand_proto protoreflect.FileDescriptor

const file_supersand_proto_rawDesc = "" +
	"\n" +
	"\x0fsupersand.proto\x12\arpc_api\"Y\n" +
	"\fErrordetails\x12#\n" +
	"\x04code\x18\x01 \x01(\x0e2\x0f.rpc_api.ErrorsR\x04code\x12$\n" +
	"\rmessagefordev\x18\x02 \x01(\tR\rmessagefordev\"0\n" +
	"\fInit_requset\x12 \n" +
	"\vAccessToken\x18\x01 \x01(\tR\vAccessToken\".\n" +
	"\x12User_login_request\x12\x18\n" +
	"\aAuthkey\x18\x01 \x01(\tR\aAuthkey\"1\n" +
	"\x15Status_comand_request\x12\x18\n" +
	"\asesonID\x18\x01 \x01(\tR\asesonID\"(\n" +
	"\fInit_respons\x12\x18\n" +
	"\asesonID\x18\x01 \x01(\tR\asesonID\"6\n" +
	"\x12User_login_respons\x12 \n" +
	"\vAccessToken\x18\x01 \x01(\tR\vAccessToken\"V\n" +
	"\x15Status_comand_respons\x12\x16\n" +
	"\x06Uptime\x18\x01 \x01(\x05R\x06Uptime\x12%\n" +
	"\x0eResource_usage\x18\x02 \x01(\x05R\rResourceUsage*\x9a\x01\n" +
	"\x06Errors\x12\x19\n" +
	"\x15Internal_Server_Error\x10\x00\x12\x10\n" +
	"\fUserNotFound\x10\x01\x12\x10\n" +
	"\fUserNotValid\x10\x02\x12\x12\n" +
	"\x0eUserLimit_full\x10\x03\x12\x12\n" +
	"\x0eNot_Accessable\x10\x04\x12\x15\n" +
	"\x11Resorces_Are_busy\x10\x05\x12\x12\n" +
	"\x0eInvalide_token\x10\x062\x87\x01\n" +
	"\fUserservices\x124\n" +
	"\x04Init\x12\x15.rpc_api.Init_requset\x1a\x15.rpc_api.Init_respons\x12A\n" +
	"\x05Login\x12\x1b.rpc_api.User_login_request\x1a\x1b.rpc_api.User_login_respons2X\n" +
	"\fSper_comands\x12H\n" +
	"\x06Status\x12\x1e.rpc_api.Status_comand_request\x1a\x1e.rpc_api.Status_comand_responsB.Z,github.com/Suman9054/supersand/proto;rpc_apib\x06proto3"

var (
	file_supersand_proto_rawDescOnce sync.Once
	file_supersand_proto_rawDescData []byte
)

func file_supersand_proto_rawDescGZIP() []byte {
	file_supersand_proto_rawDescOnce.Do(func() {
		file_supersand_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_supersand_proto_rawDesc), len(file_supersand_proto_rawDesc)))
	})
	return file_supersand_proto_rawDescData
}

var file_supersand_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_supersand_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_supersand_proto_goTypes = []any{
	(Errors)(0),                 // 0: rpc_api.Errors
	(*Errordetails)(nil),        // 1: rpc_api.Errordetails
	(*InitRequset)(nil),         // 2: rpc_api.Init_requset
	(*UserLoginRequest)(nil),    // 3: rpc_api.User_login_request
	(*StatusComandRequest)(nil), // 4: rpc_api.Status_comand_request
	(*InitRespons)(nil),         // 5: rpc_api.Init_respons
	(*UserLoginRespons)(nil),    // 6: rpc_api.User_login_respons
	(*StatusComandRespons)(nil), // 7: rpc_api.Status_comand_respons
}
var file_supersand_proto_depIdxs = []int32{
	0, // 0: rpc_api.Errordetails.code:type_name -> rpc_api.Errors
	2, // 1: rpc_api.Userservices.Init:input_type -> rpc_api.Init_requset
	3, // 2: rpc_api.Userservices.Login:input_type -> rpc_api.User_login_request
	4, // 3: rpc_api.Sper_comands.Status:input_type -> rpc_api.Status_comand_request
	5, // 4: rpc_api.Userservices.Init:output_type -> rpc_api.Init_respons
	6, // 5: rpc_api.Userservices.Login:output_type -> rpc_api.User_login_respons
	7, // 6: rpc_api.Sper_comands.Status:output_type -> rpc_api.Status_comand_respons
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_supersand_proto_init() }
func file_supersand_proto_init() {
	if File_supersand_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_supersand_proto_rawDesc), len(file_supersand_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_supersand_proto_goTypes,
		DependencyIndexes: file_supersand_proto_depIdxs,
		EnumInfos:         file_supersand_proto_enumTypes,
		MessageInfos:      file_supersand_proto_msgTypes,
	}.Build()
	File_supersand_proto = out.File
	file_supersand_proto_goTypes = nil
	file_supersand_proto_depIdxs = nil
}
