// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: supersand.proto

package rpc_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Userservices_Init_FullMethodName  = "/rpc_api.Userservices/Init"
	Userservices_Login_FullMethodName = "/rpc_api.Userservices/Login"
)

// UserservicesClient is the client API for Userservices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserservicesClient interface {
	Init(ctx context.Context, in *InitRequset, opts ...grpc.CallOption) (*InitRespons, error)
	Login(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserLoginRespons, error)
}

type userservicesClient struct {
	cc grpc.ClientConnInterface
}

func NewUserservicesClient(cc grpc.ClientConnInterface) UserservicesClient {
	return &userservicesClient{cc}
}

func (c *userservicesClient) Init(ctx context.Context, in *InitRequset, opts ...grpc.CallOption) (*InitRespons, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitRespons)
	err := c.cc.Invoke(ctx, Userservices_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userservicesClient) Login(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserLoginRespons, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserLoginRespons)
	err := c.cc.Invoke(ctx, Userservices_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserservicesServer is the server API for Userservices service.
// All implementations must embed UnimplementedUserservicesServer
// for forward compatibility.
type UserservicesServer interface {
	Init(context.Context, *InitRequset) (*InitRespons, error)
	Login(context.Context, *UserLoginRequest) (*UserLoginRespons, error)
	mustEmbedUnimplementedUserservicesServer()
}

// UnimplementedUserservicesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserservicesServer struct{}

func (UnimplementedUserservicesServer) Init(context.Context, *InitRequset) (*InitRespons, error) {
	return nil, status.Error(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedUserservicesServer) Login(context.Context, *UserLoginRequest) (*UserLoginRespons, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedUserservicesServer) mustEmbedUnimplementedUserservicesServer() {}
func (UnimplementedUserservicesServer) testEmbeddedByValue()                      {}

// UnsafeUserservicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserservicesServer will
// result in compilation errors.
type UnsafeUserservicesServer interface {
	mustEmbedUnimplementedUserservicesServer()
}

func RegisterUserservicesServer(s grpc.ServiceRegistrar, srv UserservicesServer) {
	// If the following call panics, it indicates UnimplementedUserservicesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Userservices_ServiceDesc, srv)
}

func _Userservices_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserservicesServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Userservices_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserservicesServer).Init(ctx, req.(*InitRequset))
	}
	return interceptor(ctx, in, info, handler)
}

func _Userservices_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserservicesServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Userservices_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserservicesServer).Login(ctx, req.(*UserLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Userservices_ServiceDesc is the grpc.ServiceDesc for Userservices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Userservices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc_api.Userservices",
	HandlerType: (*UserservicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _Userservices_Init_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Userservices_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "supersand.proto",
}

const (
	SperComands_Staus_FullMethodName             = "/rpc_api.Sper_comands/Staus"
	SperComands_Join_FullMethodName              = "/rpc_api.Sper_comands/Join"
	SperComands_EditServiceConfig_FullMethodName = "/rpc_api.Sper_comands/EditServiceConfig"
)

// SperComandsClient is the client API for SperComands service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SperComandsClient interface {
	Staus(ctx context.Context, in *StausComandReequest, opts ...grpc.CallOption) (*StatusComandRespons, error)
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinComandRespons, error)
	EditServiceConfig(ctx context.Context, in *EditServiceConfigRequest, opts ...grpc.CallOption) (*EditServiceConfigRespons, error)
}

type sperComandsClient struct {
	cc grpc.ClientConnInterface
}

func NewSperComandsClient(cc grpc.ClientConnInterface) SperComandsClient {
	return &sperComandsClient{cc}
}

func (c *sperComandsClient) Staus(ctx context.Context, in *StausComandReequest, opts ...grpc.CallOption) (*StatusComandRespons, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusComandRespons)
	err := c.cc.Invoke(ctx, SperComands_Staus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sperComandsClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinComandRespons, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinComandRespons)
	err := c.cc.Invoke(ctx, SperComands_Join_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sperComandsClient) EditServiceConfig(ctx context.Context, in *EditServiceConfigRequest, opts ...grpc.CallOption) (*EditServiceConfigRespons, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditServiceConfigRespons)
	err := c.cc.Invoke(ctx, SperComands_EditServiceConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SperComandsServer is the server API for SperComands service.
// All implementations must embed UnimplementedSperComandsServer
// for forward compatibility.
type SperComandsServer interface {
	Staus(context.Context, *StausComandReequest) (*StatusComandRespons, error)
	Join(context.Context, *JoinRequest) (*JoinComandRespons, error)
	EditServiceConfig(context.Context, *EditServiceConfigRequest) (*EditServiceConfigRespons, error)
	mustEmbedUnimplementedSperComandsServer()
}

// UnimplementedSperComandsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSperComandsServer struct{}

func (UnimplementedSperComandsServer) Staus(context.Context, *StausComandReequest) (*StatusComandRespons, error) {
	return nil, status.Error(codes.Unimplemented, "method Staus not implemented")
}
func (UnimplementedSperComandsServer) Join(context.Context, *JoinRequest) (*JoinComandRespons, error) {
	return nil, status.Error(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedSperComandsServer) EditServiceConfig(context.Context, *EditServiceConfigRequest) (*EditServiceConfigRespons, error) {
	return nil, status.Error(codes.Unimplemented, "method EditServiceConfig not implemented")
}
func (UnimplementedSperComandsServer) mustEmbedUnimplementedSperComandsServer() {}
func (UnimplementedSperComandsServer) testEmbeddedByValue()                     {}

// UnsafeSperComandsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SperComandsServer will
// result in compilation errors.
type UnsafeSperComandsServer interface {
	mustEmbedUnimplementedSperComandsServer()
}

func RegisterSperComandsServer(s grpc.ServiceRegistrar, srv SperComandsServer) {
	// If the following call panics, it indicates UnimplementedSperComandsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SperComands_ServiceDesc, srv)
}

func _SperComands_Staus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StausComandReequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SperComandsServer).Staus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SperComands_Staus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SperComandsServer).Staus(ctx, req.(*StausComandReequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SperComands_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SperComandsServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SperComands_Join_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SperComandsServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SperComands_EditServiceConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditServiceConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SperComandsServer).EditServiceConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SperComands_EditServiceConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SperComandsServer).EditServiceConfig(ctx, req.(*EditServiceConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SperComands_ServiceDesc is the grpc.ServiceDesc for SperComands service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SperComands_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc_api.Sper_comands",
	HandlerType: (*SperComandsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Staus",
			Handler:    _SperComands_Staus_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _SperComands_Join_Handler,
		},
		{
			MethodName: "EditServiceConfig",
			Handler:    _SperComands_EditServiceConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "supersand.proto",
}
