// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: supersand.proto

package rpc_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Errors int32

const (
	Errors_Internal_Server_Error Errors = 0
	Errors_UserNotFound          Errors = 1
	Errors_UserNotValid          Errors = 2
	Errors_UserLimit_full        Errors = 3
	Errors_Not_Accessable        Errors = 4
	Errors_Resorces_Are_busy     Errors = 5
	Errors_Invalide_token        Errors = 6
)

// Enum value maps for Errors.
var (
	Errors_name = map[int32]string{
		0: "Internal_Server_Error",
		1: "UserNotFound",
		2: "UserNotValid",
		3: "UserLimit_full",
		4: "Not_Accessable",
		5: "Resorces_Are_busy",
		6: "Invalide_token",
	}
	Errors_value = map[string]int32{
		"Internal_Server_Error": 0,
		"UserNotFound":          1,
		"UserNotValid":          2,
		"UserLimit_full":        3,
		"Not_Accessable":        4,
		"Resorces_Are_busy":     5,
		"Invalide_token":        6,
	}
)

func (x Errors) Enum() *Errors {
	p := new(Errors)
	*p = x
	return p
}

func (x Errors) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Errors) Descriptor() protoreflect.EnumDescriptor {
	return file_supersand_proto_enumTypes[0].Descriptor()
}

func (Errors) Type() protoreflect.EnumType {
	return &file_supersand_proto_enumTypes[0]
}

func (x Errors) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Errors.Descriptor instead.
func (Errors) EnumDescriptor() ([]byte, []int) {
	return file_supersand_proto_rawDescGZIP(), []int{0}
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MasterToken   string                 `protobuf:"bytes,1,opt,name=MasterToken,proto3" json:"MasterToken,omitempty"`
	SlaveToken    string                 `protobuf:"bytes,2,opt,name=SlaveToken,proto3" json:"SlaveToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_supersand_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supersand_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_supersand_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetMasterToken() string {
	if x != nil {
		return x.MasterToken
	}
	return ""
}

func (x *JoinRequest) GetSlaveToken() string {
	if x != nil {
		return x.SlaveToken
	}
	return ""
}

type InitRequset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	UniqeName     string                 `protobuf:"bytes,2,opt,name=UniqeName,proto3" json:"UniqeName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequset) Reset() {
	*x = InitRequset{}
	mi := &file_supersand_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequset) ProtoMessage() {}

func (x *InitRequset) ProtoReflect() protoreflect.Message {
	mi := &file_supersand_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequset.ProtoReflect.Descriptor instead.
func (*InitRequset) Descriptor() ([]byte, []int) {
	return file_supersand_proto_rawDescGZIP(), []int{1}
}

func (x *InitRequset) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InitRequset) GetUniqeName() string {
	if x != nil {
		return x.UniqeName
	}
	return ""
}

type UserLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccesToken    string                 `protobuf:"bytes,1,opt,name=AccesToken,proto3" json:"AccesToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginRequest) Reset() {
	*x = UserLoginRequest{}
	mi := &file_supersand_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginRequest) ProtoMessage() {}

func (x *UserLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supersand_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginRequest.ProtoReflect.Descriptor instead.
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return file_supersand_proto_rawDescGZIP(), []int{2}
}

func (x *UserLoginRequest) GetAccesToken() string {
	if x != nil {
		return x.AccesToken
	}
	return ""
}

type StausComandReequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccesToken    string                 `protobuf:"bytes,1,opt,name=AccesToken,proto3" json:"AccesToken,omitempty"`
	SesonID       string                 `protobuf:"bytes,2,opt,name=sesonID,proto3" json:"sesonID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StausComandReequest) Reset() {
	*x = StausComandReequest{}
	mi := &file_supersand_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StausComandReequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StausComandReequest) ProtoMessage() {}

func (x *StausComandReequest) ProtoReflect() protoreflect.Message {
	mi := &file_supersand_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StausComandReequest.ProtoReflect.Descriptor instead.
func (*StausComandReequest) Descriptor() ([]byte, []int) {
	return file_supersand_proto_rawDescGZIP(), []int{3}
}

func (x *StausComandReequest) GetAccesToken() string {
	if x != nil {
		return x.AccesToken
	}
	return ""
}

func (x *StausComandReequest) GetSesonID() string {
	if x != nil {
		return x.SesonID
	}
	return ""
}

type InitRespons struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SesonID       string                 `protobuf:"bytes,1,opt,name=sesonID,proto3" json:"sesonID,omitempty"`
	INItError     Errors                 `protobuf:"varint,2,opt,name=INIt_error,json=INItError,proto3,enum=rpc_api.Errors" json:"INIt_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRespons) Reset() {
	*x = InitRespons{}
	mi := &file_supersand_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRespons) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRespons) ProtoMessage() {}

func (x *InitRespons) ProtoReflect() protoreflect.Message {
	mi := &file_supersand_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRespons.ProtoReflect.Descriptor instead.
func (*InitRespons) Descriptor() ([]byte, []int) {
	return file_supersand_proto_rawDescGZIP(), []int{4}
}

func (x *InitRespons) GetSesonID() string {
	if x != nil {
		return x.SesonID
	}
	return ""
}

func (x *InitRespons) GetINItError() Errors {
	if x != nil {
		return x.INItError
	}
	return Errors_Internal_Server_Error
}

type UserLoginRespons struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	UniqeName     string                 `protobuf:"bytes,2,opt,name=UniqeName,proto3" json:"UniqeName,omitempty"`
	User_Erros    Errors                 `protobuf:"varint,3,opt,name=User_Erros,json=UserErros,proto3,enum=rpc_api.Errors" json:"User_Erros,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginRespons) Reset() {
	*x = UserLoginRespons{}
	mi := &file_supersand_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginRespons) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginRespons) ProtoMessage() {}

func (x *UserLoginRespons) ProtoReflect() protoreflect.Message {
	mi := &file_supersand_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginRespons.ProtoReflect.Descriptor instead.
func (*UserLoginRespons) Descriptor() ([]byte, []int) {
	return file_supersand_proto_rawDescGZIP(), []int{5}
}

func (x *UserLoginRespons) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserLoginRespons) GetUniqeName() string {
	if x != nil {
		return x.UniqeName
	}
	return ""
}

func (x *UserLoginRespons) GetUser_Erros() Errors {
	if x != nil {
		return x.User_Erros
	}
	return Errors_Internal_Server_Error
}

type StatusComandRespons struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sevices       int32                  `protobuf:"varint,1,opt,name=sevices,proto3" json:"sevices,omitempty"`
	ResourceUsage int32                  `protobuf:"varint,2,opt,name=Resource_usage,json=ResourceUsage,proto3" json:"Resource_usage,omitempty"`
	Joins         []*JoinRequest         `protobuf:"bytes,3,rep,name=joins,proto3" json:"joins,omitempty"`
	Errors        Errors                 `protobuf:"varint,4,opt,name=errors,proto3,enum=rpc_api.Errors" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusComandRespons) Reset() {
	*x = StatusComandRespons{}
	mi := &file_supersand_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusComandRespons) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusComandRespons) ProtoMessage() {}

func (x *StatusComandRespons) ProtoReflect() protoreflect.Message {
	mi := &file_supersand_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusComandRespons.ProtoReflect.Descriptor instead.
func (*StatusComandRespons) Descriptor() ([]byte, []int) {
	return file_supersand_proto_rawDescGZIP(), []int{6}
}

func (x *StatusComandRespons) GetSevices() int32 {
	if x != nil {
		return x.Sevices
	}
	return 0
}

func (x *StatusComandRespons) GetResourceUsage() int32 {
	if x != nil {
		return x.ResourceUsage
	}
	return 0
}

func (x *StatusComandRespons) GetJoins() []*JoinRequest {
	if x != nil {
		return x.Joins
	}
	return nil
}

func (x *StatusComandRespons) GetErrors() Errors {
	if x != nil {
		return x.Errors
	}
	return Errors_Internal_Server_Error
}

type JoinComandRespons struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Errors        Errors                 `protobuf:"varint,2,opt,name=errors,proto3,enum=rpc_api.Errors" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinComandRespons) Reset() {
	*x = JoinComandRespons{}
	mi := &file_supersand_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinComandRespons) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinComandRespons) ProtoMessage() {}

func (x *JoinComandRespons) ProtoReflect() protoreflect.Message {
	mi := &file_supersand_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinComandRespons.ProtoReflect.Descriptor instead.
func (*JoinComandRespons) Descriptor() ([]byte, []int) {
	return file_supersand_proto_rawDescGZIP(), []int{7}
}

func (x *JoinComandRespons) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *JoinComandRespons) GetErrors() Errors {
	if x != nil {
		return x.Errors
	}
	return Errors_Internal_Server_Error
}

var File_supersand_proto protoreflect.FileDescriptor

const file_supersand_proto_rawDesc = "" +
	"\n" +
	"\x0fsupersand.proto\x12\arpc_api\"P\n" +
	"\fJoin_request\x12 \n" +
	"\vMasterToken\x18\x01 \x01(\tR\vMasterToken\x12\x1e\n" +
	"\n" +
	"SlaveToken\x18\x02 \x01(\tR\n" +
	"SlaveToken\"D\n" +
	"\fInit_requset\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\x12\x1c\n" +
	"\tUniqeName\x18\x02 \x01(\tR\tUniqeName\"4\n" +
	"\x12User_login_request\x12\x1e\n" +
	"\n" +
	"AccesToken\x18\x01 \x01(\tR\n" +
	"AccesToken\"Q\n" +
	"\x15Staus_comand_reequest\x12\x1e\n" +
	"\n" +
	"AccesToken\x18\x01 \x01(\tR\n" +
	"AccesToken\x12\x18\n" +
	"\asesonID\x18\x02 \x01(\tR\asesonID\"X\n" +
	"\fInit_respons\x12\x18\n" +
	"\asesonID\x18\x01 \x01(\tR\asesonID\x12.\n" +
	"\n" +
	"INIt_error\x18\x02 \x01(\x0e2\x0f.rpc_api.ErrorsR\tINItError\"z\n" +
	"\x12User_login_respons\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\x12\x1c\n" +
	"\tUniqeName\x18\x02 \x01(\tR\tUniqeName\x12.\n" +
	"\n" +
	"User_Erros\x18\x03 \x01(\x0e2\x0f.rpc_api.ErrorsR\tUserErros\"\xae\x01\n" +
	"\x15Status_comand_respons\x12\x18\n" +
	"\asevices\x18\x01 \x01(\x05R\asevices\x12%\n" +
	"\x0eResource_usage\x18\x02 \x01(\x05R\rResourceUsage\x12+\n" +
	"\x05joins\x18\x03 \x03(\v2\x15.rpc_api.Join_requestR\x05joins\x12'\n" +
	"\x06errors\x18\x04 \x01(\x0e2\x0f.rpc_api.ErrorsR\x06errors\"N\n" +
	"\x13Join_comand_respons\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12'\n" +
	"\x06errors\x18\x02 \x01(\x0e2\x0f.rpc_api.ErrorsR\x06errors*\x9a\x01\n" +
	"\x06Errors\x12\x19\n" +
	"\x15Internal_Server_Error\x10\x00\x12\x10\n" +
	"\fUserNotFound\x10\x01\x12\x10\n" +
	"\fUserNotValid\x10\x02\x12\x12\n" +
	"\x0eUserLimit_full\x10\x03\x12\x12\n" +
	"\x0eNot_Accessable\x10\x04\x12\x15\n" +
	"\x11Resorces_Are_busy\x10\x05\x12\x12\n" +
	"\x0eInvalide_token\x10\x062\x87\x01\n" +
	"\fUserservices\x124\n" +
	"\x04Init\x12\x15.rpc_api.Init_requset\x1a\x15.rpc_api.Init_respons\x12A\n" +
	"\x05Login\x12\x1b.rpc_api.User_login_request\x1a\x1b.rpc_api.User_login_respons2\x94\x01\n" +
	"\fSper_comands\x12G\n" +
	"\x05Staus\x12\x1e.rpc_api.Staus_comand_reequest\x1a\x1e.rpc_api.Status_comand_respons\x12;\n" +
	"\x04Join\x12\x15.rpc_api.Join_request\x1a\x1c.rpc_api.Join_comand_responsB.Z,github.com/Suman9054/supersand/proto;rpc_apib\x06proto3"

var (
	file_supersand_proto_rawDescOnce sync.Once
	file_supersand_proto_rawDescData []byte
)

func file_supersand_proto_rawDescGZIP() []byte {
	file_supersand_proto_rawDescOnce.Do(func() {
		file_supersand_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_supersand_proto_rawDesc), len(file_supersand_proto_rawDesc)))
	})
	return file_supersand_proto_rawDescData
}

var file_supersand_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_supersand_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_supersand_proto_goTypes = []any{
	(Errors)(0),                 // 0: rpc_api.Errors
	(*JoinRequest)(nil),         // 1: rpc_api.Join_request
	(*InitRequset)(nil),         // 2: rpc_api.Init_requset
	(*UserLoginRequest)(nil),    // 3: rpc_api.User_login_request
	(*StausComandReequest)(nil), // 4: rpc_api.Staus_comand_reequest
	(*InitRespons)(nil),         // 5: rpc_api.Init_respons
	(*UserLoginRespons)(nil),    // 6: rpc_api.User_login_respons
	(*StatusComandRespons)(nil), // 7: rpc_api.Status_comand_respons
	(*JoinComandRespons)(nil),   // 8: rpc_api.Join_comand_respons
}
var file_supersand_proto_depIdxs = []int32{
	0, // 0: rpc_api.Init_respons.INIt_error:type_name -> rpc_api.Errors
	0, // 1: rpc_api.User_login_respons.User_Erros:type_name -> rpc_api.Errors
	1, // 2: rpc_api.Status_comand_respons.joins:type_name -> rpc_api.Join_request
	0, // 3: rpc_api.Status_comand_respons.errors:type_name -> rpc_api.Errors
	0, // 4: rpc_api.Join_comand_respons.errors:type_name -> rpc_api.Errors
	2, // 5: rpc_api.Userservices.Init:input_type -> rpc_api.Init_requset
	3, // 6: rpc_api.Userservices.Login:input_type -> rpc_api.User_login_request
	4, // 7: rpc_api.Sper_comands.Staus:input_type -> rpc_api.Staus_comand_reequest
	1, // 8: rpc_api.Sper_comands.Join:input_type -> rpc_api.Join_request
	5, // 9: rpc_api.Userservices.Init:output_type -> rpc_api.Init_respons
	6, // 10: rpc_api.Userservices.Login:output_type -> rpc_api.User_login_respons
	7, // 11: rpc_api.Sper_comands.Staus:output_type -> rpc_api.Status_comand_respons
	8, // 12: rpc_api.Sper_comands.Join:output_type -> rpc_api.Join_comand_respons
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_supersand_proto_init() }
func file_supersand_proto_init() {
	if File_supersand_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_supersand_proto_rawDesc), len(file_supersand_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_supersand_proto_goTypes,
		DependencyIndexes: file_supersand_proto_depIdxs,
		EnumInfos:         file_supersand_proto_enumTypes,
		MessageInfos:      file_supersand_proto_msgTypes,
	}.Build()
	File_supersand_proto = out.File
	file_supersand_proto_goTypes = nil
	file_supersand_proto_depIdxs = nil
}
