syntax="proto3";
package rpc_api;
option go_package = "github.com/Suman9054/supersand/proto;rpc_api";

// t stand for take and r stand for return. like Emptyt mean Emptytake or Emptyrequest.

message HandshakeReturn{
  int32 AccessToken = 1;
  int32 Refrasetoken = 2;
}

message Emptyt{};

service HandshakeService{
  rpc Handshake(Emptyt) returns(HandshakeReturn);
}

message InitReturn {
  string Sesionid = 1;
}

message Service{
  string Id = 1;
  string Lastacces  = 2;
  string ServiceUptime = 3;
  string Ramusage  = 4;
  string WorkingDir = 5;
}

message StatusReturn {
  repeated Service Services = 1;
}

enum Statusenum{
  Succes = 0;
  Failed = 1;
}

message Pullt{
  string Path = 1;
}

message Pullr{
  Statusenum Status = 1;
}

message Contaneractiont{
  string ServiceId = 1;
}

message Contaneractionr{
  Statusenum Status = 1;
  optional string message = 2;
}

service SuperCommands {
rpc Init(Emptyt) returns (InitReturn);
rpc Status(Emptyt) returns (StatusReturn);
rpc Pull(Pullt) returns (Pullr);
rpc Run(Contaneractiont) returns (Contaneractionr);
rpc Stop(Contaneractiont) returns (Contaneractionr);
rpc Delete(Contaneractiont) returns (Contaneractionr);
}

message Linuxcommandst{
  string ServiceId = 1;
  string Command = 2;
  optional string Args = 3;
}

message Linuxcommandsr{
  bytes output = 1;
}

service Linuxcommandservice{
rpc Linuxcommand(Linuxcommandst) returns (Linuxcommandsr);
}
